# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HNPGameApp' do

pod 'MJExtension'
pod 'FSScrollContentView'
pod 'SDWebImage'
pod 'AFNetworking'
pod 'Mantle'
pod 'Alamofire'

end
